### ISSUE TITLE
Where can i downloads

### ISSUE THREAD

**Issue by sebasbrs** [NoffearrDeathProjecT/DeathCore_5.4.8#2]
Hi!
where can i donload World DB?
i create server

http;//asmodeoswow.ml

Compile sucesfull in Ubuntu 12.04

Thanks

**Comment by Noffearr** [comment]
I'm still working on databases removing some mistakes! More if you want to test it use the databases that are compatible with repack because my source!

https://mega.co.nz/#!vxFGSbzZ!TNlJ1Rv1UN9H6F6cMck_q_oLlipZBS4zVn4xvuqz4QA

**Comment by sebasbrs** [comment]
i try this database thanks 

And my server will be available if they want to live testing or updates the source. I can collaborate on the project
Thank You

**Comment by Noffearr** [comment]
I'm putting the project to be deprived if you really want to help us add me to Skype to talk!

Skype My Contact: noffearrdeathproject

**Comment by sebasbrs** [comment]
ok, i add you on skype now.

my usrname is: sebas32brs 

thanks
