### ISSUE TITLE
Error Compile Ubuntu 12.04

### ISSUE THREAD

**Issue by sebasbrs** [NoffearrDeathProjecT/DeathCore_5.4.8#3]
Compile in. 
-Ubuntu 12.04 Lts 
-Cmake 3.2.1
-Libs Complete

at 22% launch this error

[ 22%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/CalendarHandler.cpp.o
[ 22%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/MiscHandler.cpp.o
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp: In member function ‘void WorldSession::HandleRequestCemeteryList(WorldPacket&)’:
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp:640:10: error: ‘range’ does not name a type
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp:642:15: error: ‘it’ does not name a type
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp:642:33: error: expected ‘;’ before ‘it’
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp:642:33: error: ‘it’ was not declared in this scope
/root/NoffearrDeathProjecT/DeathCore_5.4.8/src/server/game/Handlers/MiscHandler.cpp:642:39: error: ‘range’ was not declared in this scope
make[2]: *** [src/server/game/CMakeFiles/game.dir/Handlers/MiscHandler.cpp.o] Error 1
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make: *** [all] Error 2

**Comment by Noffearr** [comment]
Here is the normal friend should something is missing! Look:

https://travis-ci.org/NoffearrDeathProjecT/DeathCore_5.4.8

Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_the_jade_forest.cpp.o
[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_the_situation_in_dalaran.cpp.o
[ 98%] [ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_the_veiled_stair.cpp.o
[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_timeless_isle.cpp.o
[ 98%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_townlong_steppes.cpp.o
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_vale_of_eternal_blossoms.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pandaria/zone_valley_of_the_four_winds.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_dk.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_generic.cpp.o
[ 99%] [ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_hunter.cpp.o
Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_mage.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_priest.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Pet/pet_shaman.cpp.o
[ 99%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/PrecompiledHeaders/ScriptPCH.cpp.o
Linking CXX static library libscripts.a
[ 99%] Built target scripts
Scanning dependencies of target worldserver
[ 99%] [ 99%] [ 99%] [ 99%] [ 99%] [ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/CommandLine/CliRunnable.cpp.o
[ 99%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/TCSoap/TCSoap.cpp.o
[100%] Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/WorldThread/WorldRunnable.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RARunnable.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/RemoteAccess/RASocket.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Master.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/Main.cpp.o
Building CXX object src/server/worldserver/CMakeFiles/worldserver.dir/PrecompiledHeaders/worldPCH.cpp.o
Linking CXX executable worldserver
[100%] Built target worldserver
The command "make -j16" exited with 0.
Done. Your build exited with 0.

**Comment by sebasbrs** [comment]
You can help me?
i install everything that appears in travis

please give all commands please

**Comment by Noffearr** [comment]
Look man:

http://collab.kpsn.org/display/tc/Installation+Guide
